import Head from "next/head";
import { HomeStyled } from "../pageStyles/HomeStyled";
import {
  // AvatarNavWidget,
  // Navbar,
  // NavbarWidget,
  FooterWidget,
  SecHomeWidget,
  SecAboutWidget,
  SecContactWidget,
  SecProcessWidget,
  SecProfolioWidget,
  SecPartnerWidget,
  SecServiceWidget,
} from "@/widgets";
import Navbar from "@/components/Navbar/Navbar";
import Logo from "../../public/assets/images/logo.png";

export default function Home() {
  const MENU_LIST = [
    { text: "HOME", to: "Home" },
    { text: "SERVICES", to: "Service" },
    { text: "PROCESS", to: "Process" },
    { text: "PORFOLIO", to: "Profolio" },
    { text: "ABOUT", to: "About" },
    { text: "CONTACT", to: "Contact" },
  ];
  return (
    <>
      <Head>
        <title>Freedom Innovation Tech Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <HomeStyled>
        <Navbar data={MENU_LIST} image={Logo} />
        <div className="body_container_layout">
          <SecHomeWidget />
          <SecServiceWidget />
          <SecProcessWidget />
          <SecProfolioWidget />
          <SecAboutWidget />
          <SecContactWidget />
          <SecPartnerWidget />
        </div>
        <FooterWidget />
      </HomeStyled>
    </>
  );
}
